add

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,23 @@
+#!/usr/bin/env sh
+. "$(dirname -- "$0")/_/husky.sh"
 
-echo "husky is running."
-npx lint-staged
+# Check EsLint Standards
+npm run lint-check || {
+    echo 'EsLint Check Failed'
+    false
+}
+
+# Check tsconfig Standards
+npm run type-check || {
+    echo 'Type Check Failed'
+    false
+}
+
+# Run Prettier
+npm run format || {
+    echo 'Prettier Check Failed'
+    false
+}
+
+# Add Prettified files
+git add .
